### PR TITLE
Older version

### PR DESCRIPTION
**Pull request by jakorten**
Old file does not work anymore, changed to patch-5.10.87-rt59.patch.gz, but should become parameterized.

### CODE REVIEW

**Comment by jakorten** [comment]
Also see the comment as this will be an issue again soon.

**Comment by jakorten** [comment]
I rewrote part of the Dockerfile to make it variable. Now you only need to change lines 7..10 if there is a new version of raspios. I ran the script and it works for me on macOS 11.6.2 using minikube.

**Comment by remusmp** [comment]
Thanks for the contributions! Much appreciated!

One more thing needs to be done, i.e. update the .config file with the right settings. One cannot use a .config file from an older version with a newer version. I tried that a few weeks ago and the kernel, although it built fine, was not fully preempt - I had to regenerate the .config file. So my proposal here is to:
- remove .config from this repo and don't add it to the docker image anymore
- Dockerfile: use sed to disable KVM in .config
- Dockerfile: use sed to enable the RT PATCH

I don't have the time to do the above today but I will take a look these days before the new year.

**Comment by jakorten** [comment]
Great! Any hints on how to test it? Even though I have been developing software for years, working at the OS level is quite new.

**Comment by remusmp** [comment]
I have made some additional changes to make the build reproducible:
- the checkedout linux kernel repository is now a stable branch released at a fixed date
- the RT patch is now fixed and ensured to be successfully applied

I am going to close this PR as I introduced some additional changes (arguments to the Dockerfile).

**Pull request closed without merging**
